In [1]:
import pandas as pd
import os
import requests
import re
from utils import image_retrieval

In [2]:
df = pd.read_csv("pixel_prose.csv")
df.head()

,Unnamed: 0,uid,url,key,status,original_caption,vlm_model,vlm_caption,toxicity,severe_toxicity,...,width,height,original_width,original_height,exif,sha256,image_id,author,subreddit,score
0,1,c9d31cce99482e8da13f6a868e2472c3bc3ea05a874e5b...,https://thumbs.dreamstime.com/b/car-riding-wet...,7740001,success,Car riding on wet street. Car driving on wet c...,gemini-pro-vision,This image displays:\n\nA black car driving t...,0.005905,0.000017,...,800,534,800,534,{},c9d31cce99482e8da13f6a868e2472c3bc3ea05a874e5b...,NaN,NaN,-1,-1
1,2,f3a6ad643814199a98f872229758b8e735773c1803e2f1...,https://images.pexels.com/photos/770224/pexels...,7740009,success,Water Coming Out Of A Pipe,gemini-pro-vision,This image displays: A large rusty pipe with ...,0.002487,0.000007,...,500,750,500,750,{},f3a6ad643814199a98f872229758b8e735773c1803e2f1...,NaN,NaN,-1,-1
2,3,3b03f5e3a32499281dbeebb9a0e1d3dfe883bc7b72e2eb...,https://filmfare.wwmindia.com/content/2017/jul...,7740010,success,MARCH 2009 ''It's sad that a boy and girl can ...,gemini-pro-vision,This image displays: three pictures of Katrin...,0.001743,0.000003,...,600,450,600,450,{},3b03f5e3a32499281dbeebb9a0e1d3dfe883bc7b72e2eb...,NaN,NaN,-1,-1
3,4,9f3b5395744728e68b85083c0411c3b4139214f1258bf7...,https://southernersays.com/wp-content/uploads/...,7740000,success,Humpback Whale tail in the Bay of Banderas,gemini-pro-vision,This image displays:\nA photograph of a whale...,0.006152,0.000024,...,1024,662,1024,662,{},9f3b5395744728e68b85083c0411c3b4139214f1258bf7...,NaN,NaN,-1,-1
4,5,e3c7435ce411fea5656c792355a3811163da286673f8e5...,https://i.pinimg.com/originals/9a/f5/a6/9af5a6...,7740035,success,"The gaming Team logo of team DUO Team Logo, My...",gemini-pro-vision,"This image displays:\n\nText that reads ""20% ...",0.007788,0.000023,...,1820,1024,1920,1080,{},e3c7435ce411fea5656c792355a3811163da286673f8e5...,NaN,NaN,-1,-1

In [5]:
df_l_captions = pd.read_csv("./long_generated_captions.csv")

In [6]:
df_s_captions = pd.read_csv("./short_generated_captions.csv")

Empty DataFrame
Columns: [id, img_url, original_caption, paraphrased_caption]
Index: []